<a href="https://colab.research.google.com/github/Salmanndytar/Machine_leaning_classification/blob/master/Copie_de_Diabete.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score
from scipy.sparse.construct import random

In [ ]:
diabet_dataset = pd.read_csv('/content/diabetes.csv')

In [ ]:
diabet_dataset.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
#neber of rows and colomnd of data_set
diabet_dataset.shape

(768, 9)

In [ ]:
#les données statistique de data_set
diabet_dataset.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [ ]:
#les nombres de diabetique et non deibetique
# label: 0 <---non diabetiqueet 1<--- diabetique
diabet_dataset['Outcome'].value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [ ]:
#la moyenne de diabetique et non deibetique
moyennes_dibetiques_non_diabetiques=diabet_dataset.groupby('Outcome').mean()
moyennes_dibetiques_non_diabetiques

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
Outcome                                                                      
0           3.298000  109.980000      68.184000      19.664000   68.792000   
1           4.865672  141.257463      70.824627      22.164179  100.335821   

               BMI  DiabetesPedigreeFunction        Age  
Outcome                                                  
0        30.304200                  0.429734  31.190000  
1        35.142537                  0.550500  37.067164

In [ ]:
# Moyennes de tous lescolonne non diabetique
moyennes_non_diabetiques=moyennes_dibetiques_non_diabetiques.values[0]
moyennes_non_diabetiques

array([  3.298   , 109.98    ,  68.184   ,  19.664   ,  68.792   ,
        30.3042  ,   0.429734,  31.19    ])

In [ ]:
#Moyennes de tous les colonnes diabetiques

moyennes_diabetiques=moyennes_dibetiques_non_diabetiques.values[1]
moyennes_diabetiques

array([  4.86567164, 141.25746269,  70.82462687,  22.1641791 ,
       100.3358209 ,  35.14253731,   0.5505    ,  37.06716418])

In [ ]:
#calcul de risque d'atteint diabete
#moyennes_diabetiques.mean()--------->100% risque d'atteinte
#input_data--------------------------->x% risque d'atteint
# x% risue d'atteinte = (input_data * 100)/moyennes_diabetiques().mean()
input_data = (0,137,40,35,168,43.1,2.288,33)
input_risqu = np.asarray(input_data)

risuq_atteinte = (input_risqu.mean() * 100)/moyennes_diabetiques.mean()
risuq_atteinte

111.20309200541742

In [ ]:
#seperer les données et l'etiquette(Outcome):1&0
X = diabet_dataset.drop(columns='Outcome',axis=1)
Y = diabet_dataset['Outcome']

In [ ]:
print(X)
print(Y)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  


In [ ]:
#Standardisons les données-------------------------------------------
scaler = StandardScaler()

In [ ]:
scaler.fit(X)

StandardScaler()

In [ ]:
standardized_data = scaler.transform(X)
standardized_data

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [ ]:
X = standardized_data
Y = diabet_dataset['Outcome']

In [ ]:
print(X)
print(Y)

[[ 0.63994726  0.84832379  0.14964075 ...  0.20401277  0.46849198
   1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575 ... -0.68442195 -0.36506078
  -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 ... -1.10325546  0.60439732
  -0.10558415]
 ...
 [ 0.3429808   0.00330087  0.14964075 ... -0.73518964 -0.68519336
  -0.27575966]
 [-0.84488505  0.1597866  -0.47073225 ... -0.24020459 -0.37110101
   1.17073215]
 [-0.84488505 -0.8730192   0.04624525 ... -0.20212881 -0.47378505
  -0.87137393]]
0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64


Diver les donnees----> donneeTraiding et donneeTest

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size= 0.2, stratify=Y, random_state=2)

In [ ]:
print(X.shape, X_train.shape, X_test.shape)
#   X : (768, 8)donnees origine;    X_train : (614, 8) donnees d'entrainnement;  X_test:(154, 8) donnees de test

(768, 8) (614, 8) (154, 8)


Le Model de Training

In [ ]:
classificateur = svm.SVC(kernel='linear')

In [ ]:
#creer le model de classification
classificateur.fit(X_train, Y_train)

SVC(kernel='linear')

Evaluation

In [ ]:
# Score de precision sur les donnees d'entrainement
X_train_prediction = classificateur.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [ ]:
print("Score de précision des données d'entraînement",training_data_accuracy)

Score de précision des données d'entraînement 0.7866449511400652


In [ ]:
# Score de precision sur les donnees de test
X_test_prediction = classificateur.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)
print("Score de précision des données de test",test_data_accuracy)

Score de précision des données de test 0.7727272727272727


Making a prediction system

In [ ]:
input_data = (1,73,50,10,0,23,0.248,21)
#changer les donnees entree en un tableau numpy
input_data_as_numpy_array = np.asarray(input_data)

#remodeler le tableau comme nous le prévoyons pour une seule instance
input_data_modelisee = input_data_as_numpy_array.reshape(1,-1)

# Normaliser les donnees d'entree
std_data = scaler.transform(input_data_modelisee)
#print(std_data)
prediction = classificateur.predict(std_data)

risuq_atteinte = (input_data_as_numpy_array.mean() * 100)/moyennes_diabetiques.mean()
risuq_atteinte = str(round(risuq_atteinte,3))

if prediction[0] == 0 :
  print('patiant non diabetique')
  print(risuq_atteinte,"%","risque d'atteint de diabète")
else :
   print('patiant diabetique')

print() 

patiant non diabetique
43.242 % risque d'atteint de diabète



/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"
